debug: true
feign.client.config.default.loggerLevel: full

spring:
  profiles.active: local-v2
  cloud.discovery.enabled: false
  liquibase:
    enabled: true
  #    drop-first: false
  datasource:
#    url: jdbc:mysql://localhost:3307/team-club-qa?allowMultiQueries=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    hibernate:
      #none, validate, update, create-drop, create
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
  mail:
    host: localhost
    port: 1025
    username: test
    password: $2a$04$qxRo.ftFoNep7ld/5jfKtuBTnGqff/fZVyj53mUC5sVf9dtDLAi/S
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          ssl.enable: false
          auth: true
          starttls:
            enable: true

SMS:
  GW:
    PASSWORD: ''
    SMSCRoute: ''
    URL: ''
    USERNAME: ''
  MSGAT:
    apikey: ''
    userSender: ''
    username: ''



logging.level:
  #DEBUG, ERROR, FATAL, INFO, OFF, TRACE,  WARN
  root: INFO
  log4j:
    logger.searchLogger.quartz: OFF
  org:
    quartz: ERROR
    hibernate:
      SQL: OFF
      type.descriptor.sql.BasicBinder: OFF
    springframework:
      mail: DEBUG
      data: DEBUG
      jdbc.core:
        JdbcTemplate: OFF
        StatementCreatorUtils: OFF
  sa.com.stcs: debug


user-service.ribbon.listOfServers: http://localhost:6060
team-club-service.ribbon.listOfServers: http://localhost:8001
teamClub-service.ribbon.listOfServers: http://localhost:8001
otp-service.ribbon.listOfServers: http://localhost:8080
file-service.ribbon.listOfServers: http://localhost:80
notification-service.ribbon.listOfServers: http://localhost:8888
customer-service.ribbon.listOfServers: http://localhost:8052
apisix.key: edd1c9f034335f136f87ad84b625c8f1

keycloack:
  ribbon.listOfServers: http://127.0.0.1:8081
  cli_client: admin-cli
  cli_username: admin
  cli_password: admin
  cli_granttype: password

#ignore.paths:
#  - /swagger
#  - /webjars
#  - /v3/api-docs
#  #  - /v1
#  - /mail
##  - /profile


#export:
#  domain: https://qa.saudiesports.sa
#  user_db: user-qa
#  team_club_db: team-club-qa

ENV: uat
DOMAIN: https://${ENV}.saudiesports.sa/
USER_DB: user-${ENV}
TEAM_CLUB_DB: team-club-${ENV}