debug: true

feign.client.config.default.loggerLevel: full


spring:
#  cloud.discovery.enabled: false
#  liquibase:
#    enabled: true
#    drop-first: false
#  datasource:
#    username: root
#    password: root
#  #    url: jdbc:postgresql://localhost:5432/customer
#  jpa:
#    show-sql: true
#    hibernate:
#      #none, validate, update, create-drop, create
#      ddl-auto: none
#  kafka:
#    bootstrap-servers: localhost:29092
#    consumer:
#      bootstrap-servers: localhost:29092
#    producer:
#      bootstrap-servers: localhost:29092
  #  mail:
  #    protocol: smtp
  #    host: smtp.gmail.com
  #    port: 465
  ##    port: 587
  #    username: lshabory@gmail.com
  #    password: fplbcmbgzpiabklr
  #    properties:
  #      mail:
  #        debug: true
  #        transport.protocol: smtp
  #        smtp:
  #          auth: true
  #          ssl:
  #            enable: true
  #            trust: smtp.gmail.com
  #          starttls:
  #            enable: true
  mail:
    host: localhost
    port: 1025
    username: test
    password: $2a$04$qxRo.ftFoNep7ld/5jfKtuBTnGqff/fZVyj53mUC5sVf9dtDLAi/S
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          ssl.enable: false
          auth: true
          starttls:
            enable: true