https://gitlab.bluvalt.com/Esport/customer.git
https://gitlab.bluvalt.com/Esport/user.git
https://gitlab.bluvalt.com/Esport/team-club.git
https://gitlab.bluvalt.com/Esport/notifications.git
https://gitlab.bluvalt.com/Esport/otp-service.git
https://gitlab.bluvalt.com/Esport/file-mgmt.git
