CREATE DATABASE report;
CREATE DATABASE notification;


# SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = WARN;
# SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;
# SHOW STATUS LIKE 'ONGOING_ANONYMOUS_TRANSACTION_COUNT';
# SET @@GLOBAL.GTID_MODE = ON;

# CREATE DATABASE `team-club-qa`;
# CREATE DATABASE `user-qa`;
# CREATE DATABASE `team-club-uat`;
# CREATE DATABASE `user-uat`;