version: '3.5'

services:
  db_dumb:
    image: mysql
    container_name: db_dumb
    restart: always
    volumes:
      - ./dumb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3307:3306